name: CI Python Project

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade pip and install dependencies
      run: |
        pip install --upgrade pip setuptools packaging
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/ --junitxml=results.xml -v

    - name: Build package (optional)
      run: |
        python setup.py sdist bdist_wheel

    - name: Prepare artifact
      run: |
        mkdir -p staging
        cp -r dist/* staging/ || echo "No dist files found"

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: PythonPackage
        path: staging
